### PR TITLE
feat: homepage, login page, print page, navbar, smallfooter

### LINKED ISSUE #6: [Feature] 3D Printing Page
**Summary**
Create page for user to upload 3d print file, see 3d visualization of print job and push file to admin's for approval

**Text Fields**
- Submission Name
- Printer Name : DropDown of different printers available with a sort blurb under. (config file so operators could edit the printers available)
- Filament Color: Color Option (confiq file so it can be updates frequently)
- if a printer with two filament option is selected provide an option for two filaments.

**Task List**
 - [ ] Instructions to convert 3D print file to GCode
 - [x] File Upload section (drag and drop)
 - [ ] Render a visual representation of the file
 - [ ] Text Fields
 - [ ] Showcase the hours the file will require to be printed
 - [ ] Cost of printing.
 - [ ] Submit all necessary information to back end when user clicks print button

**Additional context**
https://www.figma.com/file/3C0fWZdnSGlz8fnSQOFqBT/UTDesign-Makerspace?node-id=0%3A1

### LINKED ISSUE #7: [Feature] Home Page
**Summary**
Create Home page to summarize application for new users

**Task List**
 - [x] Implement Nav Bar
 - [x] Create Hamburger menu on left side of nav bar that has account and logout buttons
 - [x] In Body summarize 3d Printing
 - [x] In Body link to external resources
 - [x] Start printing button that connect to 3D printing Page

**Additional context**
https://www.figma.com/file/3C0fWZdnSGlz8fnSQOFqBT/UTDesign-Makerspace?node-id=0%3A1

### LINKED ISSUE #15: [Feature] Login Page
**Login Page**
Created a Login Page Front end.

**Task List**
 - [x] Login Button
 - [x] Header
 - [x] Sign In information fields

### LINKED ISSUE #17: [Fix] refactor frontend to typescript & made corresponding changes
**Summary**
Refactor frontend code to be in typescript & follow `eslint` best practices

**Task List**
 - [ ] Complete refactoring all components to typescript
 - [ ] Resolve ESLint errors

**Additional context**
```
husky > pre-commit (node v16.11.1)
✔ Preparing...
⚠ Running tasks...
  ❯ Running tasks for *.{js,jsx,ts,tsx}
    ✔ prettier --write
    ✖ eslint --ext .js --ext .jsx --ext .tsx --ext .ts --ignore-path .gitignore [FAILED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...

✖ eslint --ext .js --ext .jsx --ext .tsx --ext .ts --ignore-path .gitignore:

/Users/harshasrikara/Files/Developer/Web_Projects/octopipeline/pages/index.tsx
  40:15  warning  Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
  77:15  warning  Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

/Users/harshasrikara/Files/Developer/Web_Projects/octopipeline/pages/landing.tsx
  122:22  error    `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`                                             react/no-unescaped-entities
  128:77  error    `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`                                             react/no-unescaped-entities
  141:19  warning  Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
  197:17  warning  Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
  212:24  error    `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`                                             react/no-unescaped-entities
  279:19  warning  Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
  314:19  warning  Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
  343:19  warning  Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
  378:19  warning  Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
  465:39  error    `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`                                             react/no-unescaped-entities
  477:39  error    `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`                                             react/no-unescaped-entities
  489:39  error    `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`                                             react/no-unescaped-entities

/Users/harshasrikara/Files/Developer/Web_Projects/octopipeline/pages/profile.tsx
  51:23  warning  Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

✖ 15 problems (6 errors, 9 warnings)

husky > pre-commit hook failed (add --no-verify to bypass)
```

### PR DESCRIPTION
**Pull request by Joy2469**
I used [Creative Tim Template](https://demos.creative-tim.com/notus-nextjs?ref=nnjs-readme) to make the basic structure of the website.

Edited: 
1. Tailwind.css: Added makersace color and column size w-8/12
2. Added Images: MakerSpace logo, 3D printer Image, Benchy Boat
3. Footer: Small footer with new links
4. Header: indexheader.js to edit the header. removed previous styling. edited options presented.
5. Index.js is the landing page and has the info about what 3d printing is and Steps to print
6. auth/login : created the ;login page with username and Password and LDAP files
7. print: Created a print page

Closes #15
Closes #7 
Closes #17

### CODE REVIEW

**Review by harshasrikara — CHANGES_REQUESTED** [review]
Template looks great, added small set of items to resolve in #17 before we can merge.

This branch has now been updated with the latest typescript config from `feat/mongoose` and some of the core components have already been converted to typescript. 

Make sure to run the following steps to confirm that it still works on your machine before looking into updating the PR with new changes.

```
git checkout feature/frontend

git pull

npm run dev
```

**Comment by aemmadi** [comment]
Are the extra components here from the template? Wouldn't it be better to remove the ones we don't need. Otherwise later on we would need a pretty big refactor

**Comment by harshasrikara** [comment]
> Are the extra components here from the template? Wouldn't it be better to remove the ones we don't need. Otherwise later on we would need a pretty big refactor

Yes, however, I don't think it'll cause any issues if we do keep it included. Since the entire template is local and not sitting in a node module it'll be a refactor to bring anything back if we do choose to remove it. Besides, we don't take any perf hit if the components aren't included on any of the pages

**Review by harshasrikara — APPROVED** [review]

**Review by aemmadi — APPROVED** [review]
LGTM!

**Pull request merged**
